service: pdf-generator-api

# Adopt behaviour in next version
useDotenv: true
variablesResolutionMode: "20210219"

provider:
  name: aws
  runtime: nodejs12.x
  region: ${env:AWS_BUCKET_REGION}

  # Adopt behaviour in next version
  lambdaHashingVersion: "20201221"
  apiGateway:
    shouldStartNameWithService: true

  logs:
    restApi: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:PutObjectAcl
          Resource: "arn:aws:s3:::${self:custom.bucket}/*"

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-typescript-express

custom:
  bucket: ${env:S3_BUCKET_NAME}
  serverless-offline:
    noPrependStageInUrl: true
package:
  exclude:
    - ./**
    - '!dist/**'
    - '!node_modules/**'

functions:
  generateFromHtml:
    handler: src/server.handler
    memorySize: 800
    events:
      - http:
          path: generate/from_html
          method: get
      - http:
          path: generate/from_html
          method: post
      - http:
          path: generate/from_template
          method: get
      - http:
          path: generate/from_template
          method: post
      - http:
          path: template
          method: get
      - http:
          path: file
          method: get

